CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_IDLE_TIMEOUT=2147483647
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=2147483647
CONFIG_PMW3610=y
CONFIG_PMW3610_REPORT_INTERVAL_MIN=12
